# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{xml-sax-machines}
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shane Hanna"]
  s.date = %q{2011-02-04}
  s.description = %q{XML SAX Machines}
  s.email = %q{shane.hanna@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "lib/xml-sax-machines.rb",
    "lib/xml-sax-machines/builder.rb",
    "lib/xml-sax-machines/debug.rb",
    "lib/xml-sax-machines/filter.rb",
    "lib/xml-sax-machines/fragment_builder.rb",
    "lib/xml-sax-machines/pipeline.rb",
    "test/helper.rb",
    "test/test_builder.rb",
    "test/test_debug.rb",
    "test/test_filter.rb",
    "test/test_fragment_builder.rb",
    "test/test_pipeline.rb",
    "xml-sax-machines.gemspec"
  ]
  s.homepage = %q{http://github.com/shanna/xml-sax-machines}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Assorted XML SAX readers, filters and writers.}
  s.test_files = [
    "test/helper.rb",
    "test/test_builder.rb",
    "test/test_debug.rb",
    "test/test_filter.rb",
    "test/test_fragment_builder.rb",
    "test/test_pipeline.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4"])
    else
      s.add_dependency(%q<nokogiri>, [">= 1.4"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 1.4"])
  end
end

